function h = func_h(t,in2)
%FUNC_H
%    H = FUNC_H(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    25-Nov-2024 11:37:32

y3 = in2(3,:);
y4 = in2(4,:);
h = [y3;y4;0.0;-9.81e+2./1.0e+2];
end
