function out1 = func_J(in1)
%func_J
%    OUT1 = func_J(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    25-Nov-2024 11:37:31

x1 = in1(1,:);
x2 = in1(2,:);
t2 = cos(x2);
t3 = sin(x2);
out1 = reshape([t2,t3,-t3.*x1,t2.*x1],[2,2]);
end
